version: '3.9'

services:
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification-service-dev
    ports:
      - "3007:3007"
    environment:
      PORT: 3007
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: redis-notification
      REDIS_PORT: ${REDIS_PORT}
      REDIS_TTL: ${REDIS_TTL}
      RABBITMQ_URL: ${RABBITMQ_URL}
      RABBITMQ_QUEUE: ${RABBITMQ_QUEUE}
      KAFKA_BROKER: ${KAFKA_BROKER}
      KAFKA_CLIENT_ID: ${KAFKA_CLIENT_ID}
      KAFKA_GROUP_ID: ${KAFKA_GROUP_ID}
      JWT_SECRET: ${JWT_SECRET}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_SECURE: ${MAIL_SECURE}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
      MAIL_FROM_EMAIL: ${MAIL_FROM_EMAIL}
      FRONTEND_URL: ${FRONTEND_URL}
      NODE_ENV: development
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./node_modules:/app/node_modules
    command: npm run start:dev
    networks:
      my_custom_network:
        ip4_address: ${APP_IP}

networks:
  my_custom_network:
    external: true

